### PR TITLE
parse shuffle media action

### LINKED ISSUE #6: shuffle intent is not parsed by susi_python
shuffle intent is not parsed by susi_python.
Susi_python returns an empty reply on shuffle.

### PR DESCRIPTION
**Pull request by alok760**
Fixes #6
- Parse shuffle action.
- This needs adding shuffle intent to the server as well - https://github.com/fossasia/susi_server/pull/1271

### CODE REVIEW

**Comment by norbusan** [comment]
Let us wait until this is in susi_server

**Comment by alok760** [comment]
@norbusan this can be merged now ?

**Comment by norbusan** [comment]
merged, thanks

**Comment by norbusan** [comment]
merged, thanksArggh @alok760 it was merged into `master`.

Please make your PR against `development` branch, not `master`, thanks!

**Pull request merged**
